server:
  port: 0
spring:
  application:
    name: userServer
    profile: git
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/